In [1]:
import numpy as np

# ARRAY OF 10 ZEROS

In [3]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# ARRAY OF 10 ONES

In [6]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# ARRAY OF 10 FIVES

In [7]:
five = np.ones(10)*5
five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# craete an array of all even integers from 10 t0 50

In [23]:
a = np.arange(10,51,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# create a 3x3 matrix with values ranging from  0 to 8

In [10]:
b = np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# create 3x3 identity matrix 

In [21]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Generate a random number between 0 and 1

In [32]:
x = np.random.rand()
x

0.7578710351490224

# use a numpy to generate array of 25 random numbers sampled from a standard normal distribution

In [30]:
n = np.random.rand(25)
n

array([0.14172573, 0.86348473, 0.26873434, 0.29083229, 0.36381367,
       0.46956079, 0.34750489, 0.20402045, 0.08147303, 0.90050516,
       0.74662326, 0.57931006, 0.63790879, 0.41804468, 0.28666885,
       0.20888878, 0.42738906, 0.66609145, 0.32232418, 0.17130134,
       0.80746093, 0.70053761, 0.54452152, 0.16035039, 0.99281018])

In [31]:
n = np.random.standard_normal(25)
n

array([-0.38854287,  0.32917138, -0.2639874 ,  1.26596864, -1.31084541,
       -1.43405743, -0.28482931,  0.63438706, -0.28857834,  0.29792053,
       -1.47965539,  0.650227  ,  1.46311088,  0.01489634, -0.03112858,
       -0.86034033, -0.13301007, -1.22347022, -0.11311479, -0.89099478,
       -1.03042206,  1.70618825,  0.14113407,  0.6352276 , -0.29280305])

# array of 20 linearly spaced points between 0 and 1

In [36]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [37]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [41]:
mat[3,4]

20

In [48]:
mat[0:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [49]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [50]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])